### ISSUE TITLE
Add pipelines to etc/sdssdb

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/sdssdb#214]
The user for this connection should be "my unid" instead of the generic sdss user, so how do we adapt:

```
operations:
    user: sdss_user
    admin: sdss
    host: operations.sdss.org
    port: 5432
    domain: operations.sdss.*
```

for this usecase?  ie can we just not include

```
pipelines:
    host: pipelines.sdss.org
    port: 5432
    domain: pipelines.sdss.org
```
with no mention of sdss_user, or do we need to add something dynamic which pass the output of something like get_username()?

**Comment by joelbrownstein** [comment]
I added:

```
pipelines:
    host: pipelines.sdss.org
    port: 5432
    domain: pipelines.sdss.*
```
